print("=================================================================")
print("               Resume of Prabhakar Kumar                         ")
print("=================================================================")
print("                 Name: Prabhakar Kumar                           ")
print("=================================================================")
print("          Age: 25                                                ")
print("          City: New Delhi                                        ")
print("          Country: India                                         ")
print("          Email: mk92175019@gmail.com                            ")
print("          Phone: 9217501912                                      ")
print("          Linkedin: www.linkedin.com/in/prabhakar-kumar-53b252419")
print("          Github: https://github.com/mk92175019-afk              ")
print("          Skills: Advanced Excel,python,Power BI                 ")
print("          Education: High School Diploma , Arts                  ")
print("=================================================================")
print("          Experience: 0 Years                                    ")
print("=================================================================")